# Generated by Django 3.2.7 on 2021-11-01 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0005_alter_profile_watchlist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='watchlist',
            field=models.JSONField(blank=True, default=[], null=True),
        ),
    ]
