# Generated by Django 3.2.7 on 2021-11-02 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0006_alter_profile_watchlist'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='listings_created',
            field=models.JSONField(blank=True, default=[], null=True),
        ),
    ]
