# Generated by Django 3.2.7 on 2021-11-03 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0007_profile_listings_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_img',
            field=models.ImageField(default='media/defaultprofileimage.svg', upload_to='media/'),
        ),
    ]
