# Generated by Django 3.2.7 on 2021-11-03 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0008_alter_profile_profile_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_img',
            field=models.ImageField(default='media/defaultprofileimg.svg', upload_to='media/'),
        ),
    ]
