# Generated by Django 3.2.7 on 2021-11-03 01:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Listing',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=25)),
                ('description', models.TextField(max_length=100)),
                ('price', models.SmallIntegerField()),
                ('image1', models.ImageField(blank=True, upload_to='media/')),
                ('image2', models.ImageField(blank=True, upload_to='media/')),
                ('image3', models.ImageField(blank=True, upload_to='media/')),
                ('image4', models.ImageField(blank=True, upload_to='media/')),
                ('creator_img', models.CharField(blank=True, max_length=500, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ListingLikeCount',
            fields=[
                ('listingId', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='listings.listing')),
                ('like_count', models.IntegerField(default=0)),
            ],
        ),
    ]
