# Generated by Django 3.2.7 on 2021-10-05 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0002_auto_20210930_0527'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='creator_img',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
