# Generated by Django 3.2.7 on 2021-11-16 03:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0002_alter_listing_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listing',
            name='image4',
        ),
    ]
