# Generated by Django 3.2.7 on 2021-10-20 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0003_listing_creator_img'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listing',
            name='likers',
        ),
        migrations.AddField(
            model_name='listing',
            name='like_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='listing',
            name='tags',
            field=models.JSONField(default={''}),
        ),
    ]
