# Generated by Django 3.2.7 on 2021-10-27 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0007_auto_20211027_0220'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='creator_img',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
