# Generated by Django 3.2.7 on 2021-11-02 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0008_alter_listing_creator_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='creator_img',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
