# Generated by Django 3.2.7 on 2021-09-29 11:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0002_comment_listing'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='listing',
            new_name='listingId',
        ),
    ]
