# Generated by Django 3.2.7 on 2021-09-29 14:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0003_rename_listing_comment_listingid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='listingId',
            new_name='listing',
        ),
    ]
