# Generated by Django 3.2.7 on 2021-11-02 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0004_rename_listingid_comment_listing'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='creator_img',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
