# Generated by Django 3.2.7 on 2021-11-02 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0005_comment_creator_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='content',
            field=models.TextField(blank=True, max_length=5000, null=True),
        ),
    ]
